### ISSUE TITLE
redirection link after sign up to create user page

### ISSUE THREAD

**Issue by tgabatin** [link-up-manoa/link-up-manoa#26]
Please do work for this task in a branch named issue-26.

**Comment by jatinp101** [comment]
![image](https://user-images.githubusercontent.com/42600077/81890490-cd6b5e00-9541-11ea-8226-7d93962aeba9.png)
![image](https://user-images.githubusercontent.com/42600077/81890515-de1bd400-9541-11ea-96b9-44106b9e2eb7.png)
